import type { Metadata } from "next";
import "../globals.css";
import { montserrat, oswald } from "../fonts/fonts";
import Topbar from "@/components/shared/Topbar";
import { ReduxProvider } from "@/state/provider";
import Cart from "@/components/shared/Cart";
import Footer from "@/components/shared/Footer";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Waitlist from "@/components/shared/WaitList";

export const metadata: Metadata = {
  title: "Sportx - The best sports shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body className={`${montserrat.variable} ${oswald.variable} font-sans`}>
          <Topbar />
          <Cart />
          <ToastContainer />
          <section className="flex flex-col">{children}</section>
          <div className="w-full bg-white">
            <Waitlist mode="light" />
          </div>
          <Footer />
        </body>
      </html>
    </ReduxProvider>
  );
}
1;
